### ISSUE TITLE
Mr. Goods won't give the Globe item

### ISSUE THREAD

**Issue by suloku** [mm201/pkmnFoundations#10]
Hello,

After connecting to nintendo wifi connection, Mr. Goods at Hearthome city is supposed to give to the player the "Globe" item for the secret base in the underground. Maybe having registered your location at the Geonet is a requirement too. See here for more info: http://bulbapedia.bulbagarden.net/wiki/Mr._Goods#Other

I registered at Geonet and then made a trade over the Foundations GTS, but Mr. Goods didn't give me the Globe item as it was supposed to.

My guess is that nintendo GTS enabled something in the savegame that triggered Mr. Goods to give the item, but Foundation GTS doesn't.
This is a very minor issue, but I think it should be fixed, since otherwise the Globe item will be forever lost with nintendo's GTS (for new players at least). I know I can probably hack it into the game with a save editor/AR code, but adding this to foundations GTS would be a great detail for people like me that are playing the game now instead of years ago.

I can attach a savegame that has never entered the GTS or registered at Geonet for testing if needed.

**Comment by PokeAcer549** [comment]
Sorry for huge bump, but did we ever fix this?

**Comment by mm201** [comment]
Yeah it's my bad for not knowing what to say. I don't have the spanish rom and didn't have the motivation to actually play through. Thanks for testing this. I can sleep easy now.

PS. There's no problem with "bumping" an open issue. If it's open, that means it needs any attention it can get!

**Comment by PokeAcer549** [comment]
IK this has been closed, and the bug doesn't actually occur, but I wanted to point out that I restarted again (new emuNAND too, so from scratch, new initial PID and such), and I still got the Globe on first ever connection.

**Comment by mm201** [comment]
Thank you for testing this.

**Comment by suloku** [comment]
I'll have to test again, could you please tell me where the globe is received? I assure you I tried it many times and didn't receive it, may as well test it again. Also, are you using US or EUR game (and which language)?

**Comment by PokeAcer549** [comment]
I was using a copy of Pokemon Platinum for EUR, UK English set. Go to the man in Hearthome City, and he definitely gives you it.
