### ISSUE TITLE
23404 on own server

### ISSUE THREAD

**Issue by PokeAcer549** [mm201/pkmnFoundations#15]
Hi all,
When I try to connect to my AltWFC server on any Wii game/channel I get 23404. However, the server is getting the avaliability request:
[2015-07-04 11:21:20 | GameSpyQRServer] [192.168.1.113:64754] Received availability request for 'micchannelwii' from 192.168.1.113:64754...

(micchannelwii is Wii Speak Channel, I'm looking into seeing if it works)
Also, tip to the main AltWFC server creators - add wimmfi.de as a dns resolving domain

**Comment by mm201** [comment]
Wii Speak isn't a Pokémon game. You're looking for https://github.com/polaris-/dwc_network_server_emulator
